CONTRIBUTING.md, README.md
=> ForTrilinos: added short README and CONTRIBUTING

docker/Dockerfile_stack, docker/docker-compose.yml, docker/jenkins/build.sh, docker/jenkins/config.dict, scripts/README.md, scripts/changelog.sh, scripts/docker_cmake
This is based on existing testing framework in
ORNL-CEES/DataTransferKit.
=> ForTrilinos: enable Jenkins testing based on Docker

README.md, docs/source/developer_tools.rst
- Added ReadTheDocs badge
- Added Doc reference in README
- Added some notes on SWIG usage
=> ForTrilinos: more doc update

docker/jenkins/build.sh
=> Trilinos: adding code coverage

src/epetra/src/forepetraFORTRAN_wrap.cxx, src/simple/src/fortrilinosFORTRAN_wrap.cxx, src/teuchos/src/Teuchos_Exceptions.i, src/teuchos/src/Teuchos_ParameterList.i, src/teuchos/src/forteuchosFORTRAN_wrap.cxx
Fixes the .i files for the latest SWIG fortran (after changing things to get more SWIG unit tests to pass).
=> Swig update

src/epetra/src/CMakeLists.txt, src/simple/src/CMakeLists.txt, src/teuchos/src/CMakeLists.txt
=> Install .mod files

ROADMAP.md, src/simple/test/test_simple_solver_handle_tpetra.f90, src/tpetra/src/Tpetra_MultiVector.i, src/tpetra/src/fortpetra.f90, src/tpetra/src/fortpetraFORTRAN_wrap.cxx
Implemented and fixed most things. Things remaining: 1d/2d functions +
descriptions.
=> Tpetra: multiple fixes in MultiVector

ROADMAP.md, src/simple/test/test_simple_solver_handle_tpetra.f90, src/tpetra/src/Tpetra_Map.i, src/tpetra/src/fortpetra.f90, src/tpetra/src/fortpetra.i, src/tpetra/src/fortpetraFORTRAN_wrap.cxx, src/tpetra/test/test_tpetra_map.f90, src/tpetra/tutorials/MapsAndVectors.f90, src/tpetra/tutorials/PowerMethod.f90
=> Tpetra: remove indexBase from arguments (hardcode to 1)

src/tpetra/test/CMakeLists.txt, src/tpetra/test/test_tpetra_multivector.f90
@aprokop 
All tests now pass
One TODO: `Get1dCopy` could take fortran array instead of `ArrayView`
Related issue: #121
=> Tpetra: MultiVector tests

src/tpetra/src/fortpetra.i
=> Tpetra: fixed fragment position name due to recent SWIG changes

docker/Dockerfile_stack
Don't know what changed, but the old version no longer works.
=> Updated docker file

.gitignore, scripts/autogen_tests.py
@aprokop, this is the latest version of the script I use to parse swig fortran files and auto generate unit tests.  It is a total hack, but I almost accidentally erased it and thought I'd put it out for safe storage.  It might be useful for others too.
Feel free to reject.
=> Script to auto generate unit tests

src/teuchos/test/test_teuchos_comm.f90, src/teuchos/test/test_teuchos_plist.f90, src/utils/src/fortest.f90
Use FORTRILINOS_UNIT_TEST for Teuchos.
Addresses: #153
=> ForTeuchos: Use FortanTestingUtilities.h

src/tpetra/tutorials/MapsAndVectors.f90, src/tpetra/tutorials/PowerMethod.f90
=> Removing FortranTestMacros.h from Tpetra tutorials.

src/utils/src/CMakeLists.txt
=> Do not install helper testing headers

src/tpetra/test/CMakeLists.txt, src/tpetra/test/test_tpetra_import_export.f90
=> Tpetra: Adding Import/Export tests

ReleaseNotes.txt
=> Updated ReleaseNotes.txt

src/simple/src/CMakeLists.txt, src/simple/src/eigen_handle.cpp, src/simple/src/fortrilinos_utilities.cpp, src/simple/src/fortrilinos_utilities.hpp
This will make it reproducible. Before that, the initial vector was not
initialized at all.
In the future, we would add a way for users to provide initial guess.
=> interface: set seed for the initial guess to eigenproblem

src/simple/src/eigen_handle.cpp, src/simple/src/eigen_handle.hpp, src/simple/src/fortrilinos.f90, src/simple/src/fortrilinosFORTRAN_wrap.cxx, src/simple/test/test_futility_reproducer.f90, src/simple/test/test_simple_eigen_handle.cpp, src/simple/test/test_simple_eigen_handle.f90, src/simple/test/test_simple_eigen_handle_preset.cpp
This changes API:
- Introduces `eIndex` (from Anasazi)
- Stores real and complex parts of eigenvalues
@amklinv @mattbement This may affect your work as it changes the API for the eigensystem. I still don't think the interface is final, and would like to have something better in the future. But don't have time to work on it right now. Any suggestions are welcome.
=> Allow computation for complex eigenvalues

src/tpetra/src/Tpetra_Map.i, src/tpetra/src/fortpetra.f90, src/tpetra/test/test_tpetra_crsgraph.f90, src/tpetra/test/test_tpetra_crsmatrix.f90, src/tpetra/test/test_tpetra_import_export.f90, src/tpetra/test/test_tpetra_map.f90, src/tpetra/test/test_tpetra_multivector.f90, src/tpetra/tutorials/MapsAndVectors.f90
=> Tpetra: introduce TPETRA_*_INVALID

docker/Dockerfile_stack, docker/jenkins/build.sh, docker/packages.yaml, scripts/docker_flang50_env.sh
- Update flang version
Requires gcc-7 build now and using gawk instead of mawk
- Update spack to v0.12.0
- Update cmake to 3.10.3
Trilinos develop requires 3.10+ now
=> Update Docker container

docker/jenkins/docker-compose.yml
Still don't know if this fixes CI.
=> Update docker-compose to include TRILINOS_VERSION

docs/source/install.rst
If people use our instructions, might as well do optimized build.
=> Use RelWithDebInfo instead of Debug

.jenkins, docker/Dockerfile, src/forteuchos/generated/forteuchos.F90, src/fortpetra/generated/fortpetra.F90, src/fortpetra/generated/fortpetraFORTRAN_wrap.cxx, src/fortrilinos_hl/nox_solver_def.hpp
=> Update to Trilinos 12.18.1

scripts/build-yuri.sh, src/forteuchos/forteuchos.i, src/forteuchos/generated/forteuchos.F90, src/fortrilinos_hl/fortrilinos_hl.i
This removes some configuration-dependent constants from the fortrilinos wrappers.
=> Remove configuration constants

CMakeLists.txt, README.md, doc/install.rst, doc/overview.rst, docker/Dockerfile, docker/trilinos_version, src/fortpetra/generated/fortpetra.F90, src/fortpetra/generated/fortpetraFORTRAN_wrap.cxx, test/fortpetra/test_tpetra_crsgraph.F90
A single minor change was needed for the trilinos interface. I've added documentation for the SWIG and Trilinos version compatibilities.
=> Update wrappers for Trilinos v13.0
